apiVersion: v1
kind: ConfigMap
metadata:
  name: fastapi-config
  namespace: fastapi
data:
  ENV_NAME: ${ENV_NAME}
  PROJECT_NAME: ${PROJECT_NAME}
  POSTGRES_SERVER: ${POSTGRES_SERVER}
  FRONTEND_HOST: ${FRONTEND_HOST}
  AWS_REGION: ${AWS_REGION}
  AWS_SECRET_ARN: ${AWS_SECRET_ARN}