version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10
      nodejs: 18
    commands:
      - echo "Installing tools..."
      - curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
      - chmod +x ./kubectl && mv ./kubectl /usr/local/bin/
      - curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
      - pip install pyyaml
  pre_build:
    commands:
      - echo "Injecting variables into values.yaml..."
      - python3 replace_values.py      
      - echo "Retrieving GitHub Token from Secrets Manager..."
      - export GITHUB_TOKEN=$(aws secretsmanager get-secret-value --secret-id github-token --query SecretString --output text | jq -r .token)
      - echo "GITHUB_TOKEN $GITHUB_TOKEN"
      - echo "Cloning GitOps repo..."
      - git config --global user.email "ci-bot@example.com"
      - git config --global user.name "ci-bot"
      - git clone https://x-access-token:$GITHUB_TOKEN@github.com/Piercuta/eks-karpenter-git-ops.git
      
      # - cp -r ./manifests/kustomize/* eks-karpenter-git-ops/apps/main-api/kustomize/${ENV_NAME}/patches/
      # - ls -la eks-karpenter-git-ops/apps/main-api/kustomize/${ENV_NAME}/patches/

      - cp -r ./manifests/helm/values-dev-cdk.yaml eks-karpenter-git-ops/apps/main-api/helm/
      - ls -la eks-karpenter-git-ops/apps/main-api/helm/

      - cd eks-karpenter-git-ops
      - git add .
      - git commit -m "CDK CICD K8s Main API - ${PROJECT_NAME} - ${ENV_NAME} - update all values for main-api" || echo "Nothing to commit"
      - git push
artifacts:
  files:
    - "**/*"
