# Security Group Policy
securityGroupPolicy:
  enabled: true
  securityGroupIds:
  - ${SG_MAIN_API}

# Environment variables for dev
env:
  ENV_NAME: ${ENV_NAME}
  PROJECT_NAME: ${PROJECT_NAME}
  POSTGRES_SERVER: ${POSTGRES_SERVER}
  FRONTEND_HOST: ${FRONTEND_HOST}
  AWS_REGION: ${AWS_REGION}
  AWS_SECRET_ARN: ${AWS_SECRET_ARN}

image:
  repository: ${IMAGE_URL}
  tag: ${TAG}

resources:
  limits:
    cpu: ${CPU_CAPACITY}
    memory: ${MEM_CAPACITY}
  requests:
    cpu: ${CPU_CAPACITY}
    memory: ${MEM_CAPACITY}


autoscaling:
  minReplicas: ${MIN_REPLICAS}
  maxReplicas: ${MAX_REPLICAS}

ingress:
  annotations:
    alb.ingress.kubernetes.io/certificate-arn: ${CERTIFICATE_ARN}
    alb.ingress.kubernetes.io/security-groups: ${ALB_SG_ID}
    external-dns.alpha.kubernetes.io/hostname: ${MAIN_API_DOMAIN_NAME}
  tls:
  - hosts:
    - ${MAIN_API_DOMAIN_NAME}
  rules:
  - paths:
        - path: /
          pathType: Prefix