apiVersion: v1
kind: Deployment
metadata:
  name: main-api
  namespace: main-api-${ENV_NAME}
spec:
  # replicas: ${DESIRED_REPLICAS}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 25%
  template:
    spec:
      containers:
      - name: main-api
        image: ${IMAGE_URL}
        resources:
          requests:
            cpu: ${CPU_CAPACITY}
            memory: ${MEM_CAPACITY}
          limits:
            cpu: ${CPU_CAPACITY}
            memory: ${MEM_CAPACITY}
