apiVersion: v1
kind: Deployment
metadata:
  name: file-service-app
  namespace: file-service
spec:
  replicas: ${DESIRED_REPLICAS}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 25%
  template:
    spec:
      containers:
      - name: file-service
        image: ${IMAGE_URL}
        resources:
          requests:
            cpu: ${CPU_CAPACITY}
            memory: ${MEM_CAPACITY}
          limits:
            cpu: ${CPU_CAPACITY}
            memory: ${MEM_CAPACITY}
